[project]
name = "meerkhive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonathan Kenyon", email = "jonathan.simon.kenyon@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "typer",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.9",
    "pytest>=7.1.3,<8",
    "flake8",
]

[tool.uv]
default-groups = []

[project.scripts]
meerkhive = "meerkhive:main"

[build-system]
requires = ["uv_build>=0.8.6,<0.9.0"]
build-backend = "uv_build"
